# Generated by Django 5.0.3 on 2024-06-24 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dynamics",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "动态",
                "verbose_name_plural": "动态",
            },
        ),
        migrations.AlterModelOptions(
            name="friend",
            options={"verbose_name": "好友表", "verbose_name_plural": "好友表"},
        ),
        migrations.AddField(
            model_name="friend",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="friend",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
