# Generated by Django 5.0.3 on 2024-06-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_dynamics_options_alter_friend_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamics",
            name="image",
            field=models.ImageField(blank=True, upload_to="dynamics/"),
        ),
    ]
